const { lessonStatus } = require('../../src/constants/lesson')
const mongoose = require('mongoose')

exports.fallTerm = [
	{
		lessonName: 'Bachata Nybörjare',
		danceGenre: 'Bachata',
		startDate: '2023-09-04',
		endDate: '2023-11-06',
		lessonTime: '18:00',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.INACTIVE,
		/* lessonAttendeList */
	},
	{
		lessonName: 'Bachata Fortsättning',
		danceGenre: 'Bachata',
		startDate: '2023-09-04',
		endDate: '2023-11-06',
		lessonTime: '19:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Bachata Avancerad',
		danceGenre: 'Bachata',
		startDate: '2023-09-05',
		endDate: '2023-11-07',
		lessonTime: '18:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kizomba Nybörjare',
		danceGenre: 'Kizomba',
		startDate: '2023-09-05',
		endDate: '2023-11-07',
		lessonTime: '19:30',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Valentino', 'Joan'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kizomba Fortsättning',
		danceGenre: 'Kizomba',
		startDate: '2023-09-06',
		endDate: '2023-11-08',
		lessonTime: '18:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Valentino', 'Joan'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kizomba Avancerad',
		danceGenre: 'Kizomba',
		startDate: '2023-09-06',
		endDate: '2023-11-08',
		lessonTime: '19:30',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Valentino', 'Joan'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Nybörjare',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-09-07',
		endDate: '2023-11-09',
		lessonTime: '17:30',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Fortsättning',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-09-07',
		endDate: '2023-11-09',
		lessonTime: '18:30',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.INACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Avancerad',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-09-07',
		endDate: '2023-11-09',
		lessonTime: '20:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.INACTIVE,
	},
]
