const { lessonStatus } = require('../../src/constants/lesson')

exports.springTerm = [
	{
		lessonName: 'Bachata Nybörjare',
		danceGenre: 'Bachata',
		startDate: '2023-01-30',
		endDate: '2023-04-03',
		lessonTime: '18:00',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'Bachata Fortsättning',
		danceGenre: 'Bachata',
		startDate: '2023-01-30',
		endDate: '2023-04-03',
		lessonTime: '19:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'Bachata Avancerad',
		danceGenre: 'Bachata',
		startDate: '2023-01-31',
		endDate: '2023-04-04',
		lessonTime: '18:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'LA Salsa Nybörjare',
		danceGenre: 'LA Salsa',
		startDate: '2023-01-31',
		endDate: '2023-04-04',
		lessonTime: '19:30',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Leo', 'Lisette'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'LA Salsa Fortsättning',
		danceGenre: 'LA Salsa',
		startDate: '2023-02-01',
		endDate: '2023-04-05',
		lessonTime: '18:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'LA Salsa Avancerad',
		danceGenre: 'LA Salsa',
		startDate: '2023-02-01',
		endDate: '2023-04-05',
		lessonTime: '19:30',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Nybörjare',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-02-02',
		endDate: '2023-04-06',
		lessonTime: '17:30',
		lessonDuration: 60,
		lessonFee: 1500,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Fortsättning',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-02-02',
		endDate: '2023-04-06',
		lessonTime: '18:30',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.ACTIVE,
	},
	{
		lessonName: 'Kubansk Salsa Avancerad',
		danceGenre: 'Kubansk Salsa',
		startDate: '2023-02-02',
		endDate: '2023-04-06',
		lessonTime: '20:00',
		lessonDuration: 90,
		lessonFee: 2000,
		lessonLeads: ['Andreas', 'Inka'],
		lessonStatus: lessonStatus.ACTIVE,
	},
]
